const kodePelanggaran = {
	LAWAN_ARAH: 1,
	TANPA_HELM: 2,
	TANPA_LAMPU: 3,
	LAMPU_MERAH: 4,
	SATU_ARAH: 5,
	DILARANG_PARKIR: 6,
	DILARANG_BERHENTI: 7,
	BATAS_KECEPATAN: 8,
	MELEBIHI_MUATAN: 9,
	MENGANGKUT_PENUMPANG: 10,
	DILARANG_MOBIL: 11,
	DILARANG_TRUK: 12,
};

export default kodePelanggaran;